/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscaminas;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author a.gonzalezro.2022
 */
public class FrameInfoPartidas extends javax.swing.JFrame {
    
    private static DatosCompartidosVentanas datos=new DatosCompartidosVentanas();

    /**
     * Creates new form FrameInfoPartidas
     */
    public FrameInfoPartidas() {
        initComponents();
        rellenarComboBox();
    }
    
    private void rellenarComboBox(){        
        for(Partida p : datos.getAlmacenPartidas().getListaPartida()){
            comboPartidas.addItem(p);  //Añade la partida al comboBox.
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboPartidas = new javax.swing.JComboBox<Partida>();
        verJugadores = new javax.swing.JButton();
        getMarcador = new javax.swing.JButton();
        tableroMovimientos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaSalida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Selecciona la partida:");

        comboPartidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboPartidasActionPerformed(evt);
            }
        });

        verJugadores.setText("Consultar jugadores");
        verJugadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verJugadoresActionPerformed(evt);
            }
        });

        getMarcador.setText("Ver marcador");
        getMarcador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getMarcadorActionPerformed(evt);
            }
        });

        tableroMovimientos.setText("Ver tablero inicial y movimientos");
        tableroMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableroMovimientosActionPerformed(evt);
            }
        });

        areaSalida.setColumns(20);
        areaSalida.setRows(5);
        jScrollPane1.setViewportView(areaSalida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tableroMovimientos)
                    .addComponent(getMarcador)
                    .addComponent(verJugadores)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(comboPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(comboPartidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41)
                        .addComponent(verJugadores)
                        .addGap(27, 27, 27)
                        .addComponent(getMarcador)
                        .addGap(27, 27, 27)
                        .addComponent(tableroMovimientos))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboPartidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboPartidasActionPerformed
        
    }//GEN-LAST:event_comboPartidasActionPerformed

    private void verJugadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verJugadoresActionPerformed
        Partida p=(Partida) comboPartidas.getSelectedItem();  //Recibe la partida seleccionada por el usuario.
        areaSalida.setText(p.getJugadorActual().verPerfil() + "\n" + p.getJugadorEsperando().verPerfil() + "\n"); 
        //Escribe los nombres y estadisticas de los jugadores.
    }//GEN-LAST:event_verJugadoresActionPerformed

    private void getMarcadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getMarcadorActionPerformed
        Partida p=(Partida) comboPartidas.getSelectedItem();
        Marcador marcador=p.getMarcador();
        areaSalida.setText("El marcador quedo:\n" + marcador.getMinasJ1() + " minas para " +
                p.getJugadorActual().getUsuario() + "\n" + "y " + marcador.getMinasJ2() + 
                " minas para " + p.getJugadorEsperando().getUsuario() + "\n");
    }//GEN-LAST:event_getMarcadorActionPerformed

    private void tableroMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableroMovimientosActionPerformed
        Partida p=(Partida) comboPartidas.getSelectedItem();
        areaSalida.setText(p.imprimirTablero() + "\n" + p.printMovimientos() + "\n" + "Tambien te lo he dejado en un fichero dentro de la carpeta del proyecto.\n");  //Imprime el tablero en le ventana.
        p.getAlmacenPartidas().tablero_y_movimientos(p, datos.getFicheroTableroMovimientos());
    }//GEN-LAST:event_tableroMovimientosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameInfoPartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameInfoPartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameInfoPartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameInfoPartidas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameInfoPartidas ventanaPartidas=new FrameInfoPartidas();
                ventanaPartidas.setVisible(true);
                ventanaPartidas.setLocationRelativeTo(null);
                ventanaPartidas.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaSalida;
    private javax.swing.JComboBox<Partida> comboPartidas;
    private javax.swing.JButton getMarcador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton tableroMovimientos;
    private javax.swing.JButton verJugadores;
    // End of variables declaration//GEN-END:variables
}
