/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscaminas;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author a.gonzalezro.2022
 */
public class FrameJugador extends javax.swing.JFrame {

    /**
     * Creates new form FrameJugador
     */
    
    private DatosCompartidosVentanas datos=new DatosCompartidosVentanas();
    
    public FrameJugador() {
        initComponents();
    }
   
    private void empezarPartida(){  //Comprueba si el usuario introducido es correcto y abre el tablero.
        if(datos.getUsuarios().autenticar(datos.getJugadorAux()) && datos.getJugadorAux().equals(datos.getJ1())==false){  
            //Si el segundo jugador es correcto y no es el mismo que el actual.
            for(Usuario u : datos.getUsuarios().getListaUsuarios()){  //Busca el jugador pasado en la lista.
                Jugador j2=(Jugador) u;
                if(j2.equals(datos.getJugadorAux())){  //Si se encuentra al jugador en la lista.
                    datos.setJ2(j2);
                }
            }
            FrameTableroBuscaminas nuevaPartida=new FrameTableroBuscaminas();
            nuevaPartida.setVisible(true);
            nuevaPartida.setLocationRelativeTo(null);
            nuevaPartida.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            nuevaPartida.addWindowListener(new WindowAdapter(){public void windowClosed(WindowEvent e){
                datos.organizarPartidas();
            }}); 
        }else{
            salidaMensaje.setText("Datos introducidos incorrectos.\n" + 
                    "Prueba de nuevo.\n");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nuevaPartida = new javax.swing.JButton();
        verPerfil = new javax.swing.JButton();
        verRanking = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        salidaMensaje = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Bienvenido jugador, qué te apetece hacer hoy?:");

        nuevaPartida.setText("Nueva Partida");
        nuevaPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevaPartidaActionPerformed(evt);
            }
        });

        verPerfil.setText("Ver Perfil");
        verPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPerfilActionPerformed(evt);
            }
        });

        verRanking.setText("Clasificación");
        verRanking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verRankingActionPerformed(evt);
            }
        });

        salidaMensaje.setColumns(20);
        salidaMensaje.setRows(5);
        jScrollPane1.setViewportView(salidaMensaje);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(verPerfil))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(verRanking, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addComponent(nuevaPartida)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addComponent(nuevaPartida)
                .addGap(18, 18, 18)
                .addComponent(verPerfil)
                .addGap(18, 18, 18)
                .addComponent(verRanking)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nuevaPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevaPartidaActionPerformed
        FrameCredenciales ventanaOtroJugador=new FrameCredenciales();
        ventanaOtroJugador.setVisible(true);
        ventanaOtroJugador.setLocationRelativeTo(null);
        ventanaOtroJugador.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ventanaOtroJugador.addWindowListener(new WindowAdapter(){public void windowClosed(WindowEvent e){
            empezarPartida();
        }});        
        this.dispose();
    }//GEN-LAST:event_nuevaPartidaActionPerformed

    private void verPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPerfilActionPerformed
        FramePerfil ventanaPerfil=new FramePerfil();
        ventanaPerfil.setVisible(true);
        ventanaPerfil.setLocationRelativeTo(null);
        ventanaPerfil.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_verPerfilActionPerformed

    private void verRankingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verRankingActionPerformed
        FrameRanking clasificacion=new FrameRanking();
        clasificacion.setVisible(true);
        clasificacion.setLocationRelativeTo(null);
        clasificacion.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_verRankingActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameJugador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameJugador ventanaJugador=new FrameJugador();
                ventanaJugador.setVisible(true);
                ventanaJugador.setLocationRelativeTo(null);
                ventanaJugador.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nuevaPartida;
    private javax.swing.JTextArea salidaMensaje;
    private javax.swing.JButton verPerfil;
    private javax.swing.JButton verRanking;
    // End of variables declaration//GEN-END:variables
}
