/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscaminas;
import java.awt.event.WindowListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author a.gonzalezro.2022
 */
public class FrameAvanzado extends javax.swing.JFrame {

    /**
     * Creates new form FrameAvanzado
     */
    
    private static DatosCompartidosVentanas datos=new DatosCompartidosVentanas();
    
    public FrameAvanzado() {
        initComponents();
        mensajesSalida.setEditable(false);
    }
    
    public void darAlta(){
        datos.getUsuarios().alta(datos.getJugadorAux());
        datos.getUsuarios().guardarListado(datos.getFicheroUsuarios());
    }
    
    public void darBaja(){
        datos.getUsuarios().baja(datos.getJugadorAux());
        datos.getUsuarios().guardarListado(datos.getFicheroUsuarios());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        altaJugador = new javax.swing.JButton();
        bajaJugador = new javax.swing.JButton();
        infoPartida = new javax.swing.JButton();
        cargarDesdeFichero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mensajesSalida = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Estas son las operaciones que puedes realizar como administrador:");

        altaJugador.setText("Alta jugador");
        altaJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                altaJugadorActionPerformed(evt);
            }
        });

        bajaJugador.setText("Baja Jugador");
        bajaJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaJugadorActionPerformed(evt);
            }
        });

        infoPartida.setText("Consultar Partida");
        infoPartida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoPartidaActionPerformed(evt);
            }
        });

        cargarDesdeFichero.setText("Cargar Jugadores desde archivo");
        cargarDesdeFichero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarDesdeFicheroActionPerformed(evt);
            }
        });

        mensajesSalida.setColumns(20);
        mensajesSalida.setRows(5);
        jScrollPane1.setViewportView(mensajesSalida);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(bajaJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(altaJugador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(infoPartida)
                        .addGap(144, 144, 144))))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(cargarDesdeFichero)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(altaJugador)
                .addGap(18, 18, 18)
                .addComponent(bajaJugador)
                .addGap(18, 18, 18)
                .addComponent(infoPartida)
                .addGap(18, 18, 18)
                .addComponent(cargarDesdeFichero)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void altaJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_altaJugadorActionPerformed
        FrameCredenciales ventanaAlta=new FrameCredenciales();
        ventanaAlta.setVisible(true);
        ventanaAlta.setLocationRelativeTo(null);
        ventanaAlta.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ventanaAlta.addWindowListener(new WindowAdapter(){public void windowClosed(WindowEvent e){
            if(datos.existeUsuario(datos.getJugadorAux().getUsuario())){  //Si el usuario introducido ya existe.
                mensajesSalida.setText("El usuario introducido ya esta\n" + 
                    "registrado en mi sistema.\n" + 
                        "Prueba con otro nombre.\n");
            }else{
                darAlta();            
                if(datos.getUsuarios().getListaUsuarios().contains(datos.getJugadorAux())){  //Si el usuario existe en la lista.
                    mensajesSalida.setText("El usuario ha sido registrado\n" + "satisfactoriamente.\n");
                }else{
                    mensajesSalida.setText("Ha ocurrido un error.\n");
                }
            }
        }});
    }//GEN-LAST:event_altaJugadorActionPerformed

    private void bajaJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaJugadorActionPerformed
        FrameCredenciales ventanaAlta=new FrameCredenciales();
        ventanaAlta.setVisible(true);
        ventanaAlta.setLocationRelativeTo(null);
        ventanaAlta.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        ventanaAlta.addWindowListener(new WindowAdapter(){public void windowClosed(WindowEvent e){
            darBaja();
            if(datos.getUsuarios().getListaUsuarios().contains(datos.getJugadorAux())==false){  //Si el usuario ya no existe en la lista.
                mensajesSalida.setText("El usuario ha sido borrado\n" + "satisfactoriamente.\n");
            }else{
                mensajesSalida.setText("Ha ocurrido un error.\n");
            }
        }});
    }//GEN-LAST:event_bajaJugadorActionPerformed

    private void cargarDesdeFicheroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarDesdeFicheroActionPerformed
        datos.getUsuarios().cargarListadoNuevosUsuarios(datos.getFicheroNuevosUsuarios());  //Carga un listado de usuarios de un fichero.txt
        mensajesSalida.setText("Jugadores cargados.\n");
    }//GEN-LAST:event_cargarDesdeFicheroActionPerformed

    private void infoPartidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoPartidaActionPerformed
        FrameInfoPartidas ventanaPartidas=new FrameInfoPartidas();
        ventanaPartidas.setVisible(true);
        ventanaPartidas.setLocationRelativeTo(null);
        ventanaPartidas.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_infoPartidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameAvanzado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrameAvanzado avanzado=new FrameAvanzado();
                avanzado.setVisible(true);
                avanzado.setLocationRelativeTo(null);
                avanzado.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton altaJugador;
    private javax.swing.JButton bajaJugador;
    private javax.swing.JButton cargarDesdeFichero;
    private javax.swing.JButton infoPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea mensajesSalida;
    // End of variables declaration//GEN-END:variables
}
