/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscaminas;

/**
 *
 * @author a.gonzalezro.2022
 */
public class FramePerfil extends javax.swing.JFrame {
    
    private static DatosCompartidosVentanas datos=new DatosCompartidosVentanas();

    /**
     * Creates new form FramePerfil
     */
    public FramePerfil() {
        initComponents();   
        areaEscritura.setText(datos.getJ1().verPerfil());
        rellenarComboBox();
    }
    
    private void rellenarComboBox(){
        for(Usuario j : datos.getUsuarios().getListaUsuarios()){  //Recorre los usuarios registrados.
            if(datos.getJ1().equals(j)==false){  //Se guardan los usuarios que no son el actual.
                jugadoresBoton.addItem(j);  //Añade el jugador al botón.
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        areaEscritura = new javax.swing.JTextArea();
        comparacionBoton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jugadoresBoton = new javax.swing.JComboBox<Usuario>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        areaEscritura.setColumns(20);
        areaEscritura.setRows(5);
        jScrollPane1.setViewportView(areaEscritura);

        comparacionBoton.setText("Comparar con este Jugador");
        comparacionBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comparacionBotonActionPerformed(evt);
            }
        });

        jLabel1.setText("Elegir otro Jugador para compararte:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(comparacionBoton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addGap(40, 40, 40)
                        .addComponent(jugadoresBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jugadoresBoton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(comparacionBoton)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comparacionBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comparacionBotonActionPerformed
        Jugador jugadorOtro=(Jugador)jugadoresBoton.getSelectedItem();  //Recibe el nombre del jugador seleccionado.;
        datos.getJ1().crearComparativa(jugadorOtro);  //Crea la comparativa entre los dos jugadores. 
        if(jugadorOtro.getPartidasJugadas().isEmpty()){  //Si la lista de partidas del otro jugador est vacía.
            areaEscritura.setText("Este usuario aun no ha jugado.\n");
        }else{
            areaEscritura.setText(datos.getJ1().getComparativa().compararJugadores()); 
        }       
    }//GEN-LAST:event_comparacionBotonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FramePerfil ventanaPerfil=new FramePerfil();
                ventanaPerfil.setVisible(true);
                ventanaPerfil.setLocationRelativeTo(null);
                ventanaPerfil.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaEscritura;
    private javax.swing.JButton comparacionBoton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Usuario> jugadoresBoton;
    // End of variables declaration//GEN-END:variables
}
