/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package buscaminas;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;

/**
 *
 * @author a.gonzalezro.2022
 */
public class FrameGameOpening extends javax.swing.JFrame {
    
    private static DatosCompartidosVentanas datos=new DatosCompartidosVentanas();

    /**
     * Creates new form FrameGameOpening
     */
    public FrameGameOpening() {
        initComponents();
        datos.getUsuarios().cargarListado(datos.getFicheroUsuarios());  //Carga la lista de usuarios.
        datos.getAlmacenPartidas().cargarFichero(datos.getFicheroPartidas());  //Carga la lista de partidas.
        datos.organizarPartidas();
    }
    
    private void cierre(){
        datos.getUsuarios().guardarListado(datos.getFicheroUsuarios());
        datos.getAlmacenPartidas().guardarFichero(datos.getFicheroPartidas());  //Guarda la lista de todas las partidas.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        InicioAdmin = new javax.swing.JButton();
        LogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(1200, 600));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/buscaminas/PortadaBuscamins(1000x353).png"))); // NOI18N
        jLabel2.setText("jLabel2");

        InicioAdmin.setText("Iniciar sesión admin");
        InicioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioAdminActionPerformed(evt);
            }
        });

        LogIn.setText("Iniciar sesión Jugador");
        LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(458, 458, 458)
                .addComponent(InicioAdmin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogIn)
                .addGap(468, 468, 468))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InicioAdmin)
                    .addComponent(LogIn))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InicioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioAdminActionPerformed
        FrameAdmin ventanaAdmin=new FrameAdmin();  //Abre la ventana para pedir los datos del administrador.
        ventanaAdmin.setVisible(true);
        ventanaAdmin.setLocationRelativeTo(null);
        ventanaAdmin.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_InicioAdminActionPerformed

    private void LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogInActionPerformed
        FrameLogIn inicioSesion=new FrameLogIn();
        inicioSesion.setVisible(true);
        inicioSesion.setLocationRelativeTo(null);
        inicioSesion.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_LogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameGameOpening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameGameOpening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameGameOpening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameGameOpening.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                FrameGameOpening frame=new FrameGameOpening();
                frame.setVisible(true);
                frame.setLocationRelativeTo(null);
                frame.addWindowListener(new WindowAdapter(){public void windowClosed(WindowEvent e){
                    frame.cierre();
                }});
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton InicioAdmin;
    private javax.swing.JButton LogIn;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
